enabled: true
default_lang: en
dropdown:
  enabled: true

streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '':
          - user/themes/gregthemetwo
          - user/themes/antimatter
#      paths:
#        - user/themes/gregTheme
