title: gChambers
author:
  name: Gregory Chambers
  email: 'greg@gChambers.com'
blog:
  route: ''
metadata:
    description: 'Sandbox site dedicated to understanding and practice of proper front-end web design'
taxonomies: [category,tag,month]

summary:
  enabled: true                             # enable or disable summary of page
  format: long                             # long = summary delimiter will be ignored; short = use the first occurrence of delimiter or size
  size: 900                                 # Maximum length of summary (characters)
  delimiter: ===                            # The summary delimiter


redirects:
#  /redirect-test: /                         # Redirect test goes to home page
#  /old/(.*): /new/$1                        # Would redirect /old/my-page to /new/my-page

routes:
#  /something/else: '/blog/sample-3'         # Alias for /blog/sample-3
#  /new/(.*): '/blog/$1'                     # Regex any /new/my-page URL to /blog/my-page Route

menu:                                      # Sample Menu Example
#    - text: Source
#      icon: github
#      url: https://github.com/getgrav/grav
#    - icon: twitter
#      url: http://twitter.com/getgrav

# ++++++++++++++++++++
# Items below display in footer area. They work in conjunction with /user/themes/gregthemetwo/templates/partials/base.html.twig
# ++++++++++++++++++++
copyright:
    text1: Copyright
    startYear: 2014
    url: http://gChambers.com
    text2: gChambers

# copyright2:
#     text1: "additional Attribution"
#     url: http://getgrav.org/
#     text2: Grav Team
# ++++++++++++++++++++!
