home:
  alias: '/blog'

pages:
  theme: gregTheme
  markdown:
    extra: true     # False by default; copied from system/config/system.yaml
  process:
    markdown: true
    twig: false

markdown:
  extra: true

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
  gzip: true

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
  collections:
    jquery: system://assets/jquery/jquery-2.x.min.js

debugger:
  enabled: false
  shutdown:
    close_connection: true

images:
  default_image_quality: 85                 # Default image quality to use when resampling images (85%)
  cache_all: true                          # Cache all image by default
  cache_perms: '0755'                       # MUST BE IN QUOTES!! Default cache folder perms. Usually '0755' or '0775'
  debug: false                              # Show an overlay over images indicating the pixel depth of the image when working with retina for example

media:
  enable_media_timestamp: true             # Enable media timetsamps
  upload_limit: 800                           # Set maximum upload size in bytes (0 is unlimited)
  unsupported_inline_types: []              # Array of supported media types to try to display inline
  allowed_fallback_types: []                # Array of allowed media types of files found if accessed via Page route
